
export enum TypeAPI{
	UNDEFINED = "UNDEFINED",
	ACTION = "ACTION",
	CARD = "CARD",
	CARD_CONTROL = "CARD_CONTROL",
	CARD_CONTROL_ACTION = "CARD_CONTROL_ACTION",
	TEXT = "TEXT",
	DIALOG = "DIALOG",
	MENU = "MENU",
}